README.md
Current list of stages:
Implemented, Approved, Under review, Draft, Work in Progress, Dropped
=> Organize tables by stage of document

README.md
FYI @meisterT @laszlocsomor @buchgr
=> Replace Googler aliases with their GitHub users.

README.md
=> Add Bazel Runfiles Libraries doc

README.md
Review thread: https://groups.google.com/d/msg/bazel-dev/Vnugr-wDTqU/0tKcYkkyBwAJ
=> Add link: "Test execution on Windows without Bash"

README.md
This just adds the link, will do the actual review in https://github.com/bazelbuild/proposals/pull/21
=> Add link to Toolchain Modes PR for review.

README.md
Design proposal for https://github.com/bazelbuild/bazel/issues/6426
=> Submit 'Old Flags to Platforms Migration' for review

README.md
Adds a document that is currently under review which exposes parts of the C++ Skylark API.
=> Update proposals with C++ API doc

README.md
Addresses https://github.com/bazelbuild/proposals/pull/4#issuecomment-433424306
cc @damienmg
=> Fix WORKSPACE docs and attribution.

README.md
This is the design doc for `bazelbuild/bazel` issue
https://github.com/bazelbuild/bazel/issues/2832
=> Multiplex persistent worker

README.md
Multiplex worker proposal approved
=> Multiplex worker approved

designs/2019-01-14-delayed-load.md
WORKSPACE files are evaluated in Skyframe. This is based on
computations for Skykeys and restarts of those computations.
Hence the implementaiton is not as straight forward as the
description of generating and enforcing thunks suggests.
Nevertheless, it is possible by extending the respective
Skykeys. Describe how.
=> delayed loading: describe a possible implementation

designs/2019-02-12-execution-transitions.md, designs/2019-02-12-toolchain-transitions.md
Reflects the latest comments from the design review thread.
Please comment only on formatting and style: actual design discussion should still take place at [the review thread](https://groups.google.com/forum/!msg/bazel-dev/5osWxhoF0Fk/1yw4MXrEBQAJ).
=> Update toolchain transitions design

README.md
part of https://github.com/bazelbuild/bazel/issues/7766
=> Added draft proposal - Propagate tags from the targets to the actions

README.md
According to [design policy](https://bazel.build/designs/index.html), this PR is just to switch the status for "In Review", not to actually approve the review.
After this PR is in I'll start a bazel-dev discussion to kick off review proper.
=> Set "Common Bazel Constraints" to Under Review.

README.md
According to [design policy](https://bazel.build/designs/index.html), this PR is just to switch the status for "In Review", not to actually approve the review.
After this PR is in I'll start a bazel-dev discussion to kick off review proper.
=> Change output path proposal to Under Review.

README.md, designs/2019-04-29-cache.md
...as it has been approved in today's design meeting.
=> Mark "forcing non cache hits" as approved

designs/2018-10-22-autoconfigured-host-platform.md
Starting to pick this back up, so I am updating the rollout plan.
=> Update the proposal for the current state of the codebase.

README.md, designs/2019-06-25-platforms-strategies.md
=> Add a new design proposal to directly tie together execution platforms

README.md
Please also assign reviewers. Is @hlopko a good fit as lead reviewer?
Thanks!
=> Require load() statement for protobuf rules

README.md
Please also assign reviewers (maybe @hlopko and @lberki). 
Thanks!
=> Add proposal "Replacing native <lang>_proto_library rules with Starlark"

README.md
A proposal for allowing execution properties to be set on a target directly, allowing the user to decouple it from platform resolution
=> Adding a proposal for Target-level execution properties

README.md, designs/2019-11-11-target-platform-constraints.md
This is a draft: please comment only on formatting, grammar, etc, and not on the content. Once accepted I'll mark it as Under Review and begin to publicize.
=> Add draft proposal to expose target platform constraints to Starlark

README.md, designs/2019-11-11-target-platform-constraints.md
Starting the review process, hooray
=> Move target platform constraints to In Review

README.md, designs/2019-11-11-target-platform-constraints.md
Implementation tracked from: https://github.com/bazelbuild/bazel/issues/10368
=> Mark "Exposing Target Platform Constraints" as implemented.

README.md
Plans for implementation of https://github.com/bazelbuild/bazel/issues/7444
=> Add pointer to license proposal

README.md
Following from this thread in [bazel-discuss](https://groups.google.com/d/msg/bazel-discuss/895-OjU2Z2A/Yi5ADPWyBQAJ), starting a draft proposal on Starlark based project files.
=> Add Starlark project files

README.md
Adding a Proposal for Bazel Package Validators
=> Adding proposal for Bazel PackageValidators

README.md, designs/2019-02-12-toolchain-transitions.md, designs/2020-02-07-toolchain-transition-migration.md
transition.
Note that this is a draft proposal: please limit PR review to formatting issues, actual design review will take place on the discussion thread.
=> Propose a different plan for migrating rules to use the toolchain

README.md, designs/2020-02-07-toolchain-transition-migration.md
=> Move Toolchain Transitions Migration to under Review.

README.md, designs/2020-05-13-toolchain-context-dependencies.md
configured target key.
This is a draft, and not sent for review yet. Please only comment on formatting issues, as the design discussion will start on bazel-discuss.
=> Add a proposal to pass toolchain context information as part of the

README.md
This is a proposal for an internal capability to define builtin symbols in Starlark instead of Java.
=> Add 'Injecting Starlark Values ...'

README.md
Per https://bazel.build/designs/index.html#create-a-pull-request, creating a PR for a new design "Starlark Directory Expansion in Args MapEach".
=> Starlark Directory Expansion in Args MapEach

README.md, designs/2020-09-29-new-default-target-constraint.md
The proposal would inevitably bring a difference to target and host platform running on the same machine. Looking for an alternative solutions.
=> Drop "Adding a constraint to default target platform" proposal.

README.md
This moves the documents most likely to be looked at closer to the top,
instead of having to scroll down over an ever-increasing number of
documents in the "Implemented" state.
=> Reorder the different states.

README.md
https://docs.google.com/document/d/1WPq2g__IwrsSsxn4-rcfTSQODDtnKQTDhnHvtA37nlQ/edit?usp=sharing
=> Add Aspects propagating other aspects design document

README.md, designs/2021-07-08-monorepo-toolchain-registration.md
Adding Draft proposal to start the process.
=> Monorepo toolchain registration

README.md
Add design doc proposal for the addition of the `subpackages()` built-in helper function
=> Add Proposal for subpackages helper function

README.md
Subpackages has been implemented and merged to head
=> Move subpackages proposal to implemented

README.md, designs/2022-01-21-optional-toolchains.md
This is just to begin the design discussion, not to set the proposal as complete.
=> Add design proposal for optional toolchains

designs/2022-01-21-optional-toolchains.md
Clarify that mandatory toolchains will cause execution platforms to be ignored.
Clarify definition of "priority".
=> Updates from design review

README.md
https://docs.google.com/document/d/1uyJjkKbE8kV8EinakaR9q-Un25zCukhoH_dRBkWHSKQ
=> Add proposal for renaming applicable_liceneses

README.md
Adds a proposal for a more modular c++ toolchain api.
cc @tpudlik (pigweed team)
I'm not sure who to add as a primary reviewer. I think @oquenchil is listed as the contact point for the ream-rules-CPP. Are you available to review this proposal?
I'll be working on an implementation for this proposal while it goes through review, @tpudlik has agreed to review the actual implementation as I go.
=> Add proposal for modular cc toolchains

README.md, designs/2022-01-21-optional-toolchains.md
- Optional Toolchains is Implemented
- Exec Platforms vs Strategies is Dropped (pending being rewritten)
=> Update status on proposals

README.md
There was no agreement on the matter.
=> Drop "Starlark fail(errorcode=)".

README.md
=> Delete "OSS Licenses and Bazel Dependency Management".

README.md
* "Renaming applicable_licenses" is now approved
* "OSS License Declarations" is not implemented
=> Update some design docs related to licensing:

README.md, designs/2023-06-08-standard-platform-transitions.md
Please review for syntactic correctness, I'll start the review thread once this is public.
=> Add the base proposal for Standard Platform Transitions.

README.md, designs/2023-06-08-platform-based-flags.md
Uploading initial proposal prior to starting the design review process.
=> Add the initial proposal for platform-based flags.

designs/2022-06-07-bazel-credential-helpers.md
=> Replace "url" with "uri" in credential helpers proposal to match the implementation.

README.md
Historically, we haven't been very good at this so let's not promise something we can't do.
=> Do not promise that live documents are updated.

designs/2023-06-08-platform-based-flags.md
Mostly has sdtwigg's notes on flag semantics.
Once this is merged we can discuss in the thread
=> Update platform-based flags based on the discussion.

README.md
@Wyverald @meteorcloudy @cgrindel I worked in the final results of the discussions, could you take another look and approve?
=> Rename and move `bazel mod fix` to "Approved"

README.md, designs/2023-06-04-exec-platform-scoped-spawn-strategies.md
Revisions from feedback at https://github.com/bazelbuild/bazel/discussions/20497
=> Incorporating feedback from review of exec platform scoped spawn strategies proposal

README.md
also moved "directory watching API for repo rules" to Implemented.
=> add "a new home for host platforms"

README.md, designs/2024-04-16-transition-composition.md
This is putting the proposal up to begin discussion. Please limit review to formatting and syntax, I'll start a design discussion once this is available.
=> Add a short proposal about composing starlark transitions.

README.md
Rename "latent dependencies" to "dormant dependencies" in the catalog.
=> Rename "latent deps" to "dormant deps" in the catalog

README.md
Also drop the original version.
=> Add new version of dormant deps.

README.md, designs/2023-06-04-exec-platform-scoped-spawn-strategies.md
Moving this into "approved" as requested by @katre https://github.com/bazelbuild/bazel/discussions/20497#discussioncomment-10138787
=> Move exec platform scoped spawn strategies into approved

README.md
=> Add "Per-target execution platform constraints for exec groups" to drafts

README.md
Also move some implemented external dep proposals to "implemented"
=> Add optional/nodep external deps

README.md, designs/2025-06-18-sh-toolchain-for-run-shell.md
https://github.com/bazelbuild/bazel/issues/26326
https://github.com/bazelbuild/bazel/issues/5265
=> add doc for sh_toolchain for run_shell.
