- README.md
This re-adds the leading and ending pipes for table markdown formatting. Without the pipes, editors are unable to detect that the text chunk as a markdown table to apply automatic formatting, even though Github renders it properly.
Preview: https://github.com/bazelbuild/proposals/blob/f19f4cd0d975233c5dc5c514c4946ce7890f81fc/README.md
> Add the leading and ending pipes for table markdown formatting

- designs/2018-07-13-repository-hashing.md
> Fix spelling error in Bazel Hashing Doc

- README.md
and link to bazel-dev instead of bazel-discuss
> Add link to the design process

- README.md
- designs/2018-10-29-external-repositories-reporting.md
It is a long-standing feature request to be able to report progress
about fetching external repositories. As currently, there is way for
Starlark repository rules to do so, this document proposes an extension
of the external-repositories build API to allow reporting of progress.
> Add a proposal to report progress of external repositories

- README.md
- designs/2018-11-27-meta-rules.md
This concept is implicit in the design of the format of resolved
files. So let's add a draft working out the details.
> Add a draft on repository rules with multiple return values

- README.md
- designs/2019-03-21-download-failures.md
For actions in repository rules (initiated by ctx.execute) the exit
code of the action is passed on to the repository rule so that it
can use it to handle the failure of the action or use actions to
probe parts of the environment. For downloads, however, any failure
is fatal and the whole repository rule is aborted. This proposal
argues that allowing rules to handle download failures is a useful
extension of the build API.
> Add a proposal to allow repository rules to handle download failures

- designs/2019-04-04-starlark-dependencies-pruning.md
> Starlark dependencies pruning

- README.md
- designs/2019-03-21-download-failures.md
It was approved in the meeting on Apr 4, 2019 and implemented
by https://github.com/bazelbuild/bazel/commit/b9f0585f934ce19af0b6e2d464051865a741a733
> Marks handling of download failures as implemented

- README.md
- designs/2019-04-29-cache.md
Bazel has a "repository cache", which contains files indexed by
their hash. While a hash is a good way to identify the contents of
a file, there are situations, where the rule author does not think
of the hash as identifying the file and wants to force a redownload
under certain conditions, in case the hash is "wrong". This document
discusses possible implementations.
> Add a design on additional conditions for repository cache lookup

- README.md
The link to the design document was to the forked repository.
Updated it to be as relative to the repo.
@aehlig Should I open a discussion in `bazel-dev` about the design?
> updated a url to a local repo for design document

- README.md
- designs/2019-04-29-cache.md
It has been implemented in
https://github.com/bazelbuild/bazel/commit/4d62d74b645d3af31840593cd490398cee0d91ae and
https://github.com/bazelbuild/bazel/commit/c917ab208942e7b250e4dc928863a56ea2bdaee3
> Mark cache splitting as implemented

- README.md
- designs/2019-05-27-auth.md
Add a document describing a modified version of the previous proposal
on authentication for downloads in external repositories. This modified
proposal is the outcome of a discussion of the respective bazel team,
taking into account the previous proposal and the discussion on the
mailing list.
> Add a modified proposal for authentication in downloads

- README.md
- designs/2019-05-27-auth.md
It was approved in the Starlark meeting at June 6, 2019
and the implementation completed in 26e3396cb341e173b4be5c780cafac3ec386df5.
Also add a clarifying statement that http_archive will by
default honor a `.netrc` file even though this will not
be part of the build API, but instead an implementation
detail of the corresponding Starlark rule.
> Mark authentication design as implemented

- designs/2019-10-15-tool-visibility.md
The current semantics of checking visibility for private attributes could
be used to work around the absence of a concept of visibility for rules
themselves. With the proposed change, this is no longer possible.
Document that restriction.
> tool visibility design: also document possible uses of the old semantics

- designs/2019-10-15-tool-visibility.md
In the background section of the tool-visibility proposal,
add a simplified example showing how visibility rules make it
hard to evolve the interface of an internal tool. A real-world
example was already linked in the background section but is
more involved due to additional indirections.
> tool visibility: add an example

- README.md
- designs/2019-10-24-file-visibility.md
Files currently get exported with default visibility if needed as a dependency in the
same package. This proposal suggests a less fragile semantics.
> Adding a proposal for changing visibility for files

- designs/2019-10-24-file-visibility.md
...highlighting the aspect that exposure with default
visibility happens independent of the visibility of the
target using the source file.
> file visibility: extend the example section

- README.md
- designs/2019-05-27-auth.md
The "Authentication for `ctx.download`" proposal was listed twice in
README.md, under implemented and under review. As implemented is correct,
remove the duplicate entry under review. Also, correct the state that is
mentioned in the proposal itself.
> README.md: clean up duplicate entry

- README.md
- designs/2019-10-24-file-visibility.md
It has been approved and the flag was added in
https://github.com/bazelbuild/bazel/commit/2bb1bf9422ba22d0e1ab15363664339f022b29a1
> Mark file visibility as implemented

- README.md
Based on further discussion on the proposal in [bazel-discuss](https://groups.google.com/d/msg/bazel-discuss/895-OjU2Z2A/ha2gEEPODgAJ), until there's a clear reason for the project files to need to be interpretable/starlark based we will drop this proposal for now and instead implement static parameter files.
> Drop Starlark project files proposal

- README.md
- designs/2020-01-14-remote-downloads.md
Per email discussion, this takes the two existing proposals for remote downloading of external dependencies ([Remote Repository Cache](https://docs.google.com/document/d/1aagKnM8kRmMvLqSXasShsI-NYOBZYtgNrbYWLPwBoBg/view) and [Remote 'Fetch' API](https://docs.google.com/document/d/10ari9WtTTSv9bqB_UU-oe2gBtaAA7HyQgkpP-RFP80c/view)) and merges them into the Bazel proposals repository.
The Protobuf portions of the merged proposal are copied from the Fetch API doc, because that's the version that got approved by Bazel + RBE devs. The Bazel-specific portions (e.g. implementation plan) plus a bunch of the background/motivation is from the Remote Repository Cache doc.
I tried my best to keep both the spirit and details of both documents intact. If there's anywhere the authors of the Fetch API …
> Unify remote downloader proposals (remote repo cache, remote fetch api)

- README.md
This was moved to dropped in #165, but seems to have been accidentally re-added when merging 4179d9f219a48872b72674c878168644ed77be62.
> Re-move starlark project files to dropped.

- designs/2020-02-07-toolchain-transition-migration.md
Addressing most recent round of review comments. I've added text specifically about the types of failures we've seen in exec transition changes, in hopes that this will help rule authors test and verify their toolchains.
> Expand further on exec depdency migration steps.

- README.md
In accordance with design review policy, this is just to put the doc in the registry, not the actual review.
> Under review: "Measuring Configuration Overhead"

- README.md
Make remote execution calls keepalived to avoid Bazel hanging indefinitely due to network issues. This could be one of the reasons causing Bazel to hang forever. The hanging issue is reported at https://github.com/bazelbuild/bazel/issues/11782.
> Add "Keepalived remote execution"

- designs/2021-02-09-remote-output-service.md
@alexjski made a fair point on the mailing list thread last week that it
may make sense to make the output path completely read-only. I agree,
though it would break unsandboxed actions.
For now, let's stick to keeping the output path writable, but at least
add a section to the proposal on what needs to be done to make it
read-only in the future.
> Remote Output Service: Mention read-only output paths

- README.md
- designs/2021-08-10-rules-authors-sig.md
We propose to form a Special Interest Group (SIG) among authors of commonly used Bazel rulesets.
The intent is for these engineers to share technical approaches for solving common problems,
to have a single coherent voice for interacting with the core Bazel team,
and to provide a more consistent experience for Bazel end-users.
> rules authors SIG proposal

- README.md
- designs/2022-03-06-representation-of-repeatable-starlark-flags.md
This proposal was requested by @gregestren in https://github.com/bazelbuild/bazel/pull/14911#issuecomment-1059564103.
> Add "Representing repeatable Starlark flags as config.string_list"

- designs/2022-03-06-representation-of-repeatable-starlark-flags.md
@gregestren Forgot to replace the template for this section, sorry.
> Add abstract to "Representing repeatable Starlark flags as config.string_list"

- designs/2022-03-06-representation-of-repeatable-starlark-flags.md
@aranguyen @gregestren This is the update to the proposal following the result of our discussion.
> Use boolean instead of string parameter for repeatable Starlark flags

- designs/2022-07-21-locating-runfiles-with-bzlmod.md
Updates the proposal with:
* changes suggested in a discussion with @lberki and @wyverald
* changes required due to canonical repository names no longer starting with `@`
* the observation that non-tool toolchain dependencies also have to have their repository mappings tracked
> Update "Locating Runfiles with Bzlmod"

- README.md
It's been stalled for more than a year.
> Drop "Guidance for Rules Authors how to deal with Bazel versions".

- README.md
The landscape has changed since then; it still makes sense to use toolchains in proto rules, but it will probably be done somewhat differently when we get to it.
> Drop "Toolchainifying proto rules."

- README.md
@katre  already reviewed this, and I've started implementing. But we didn't share this publicly. Doing so now to update the community and solicit wider feedback.
Note this doc is generic in its ideas but  focused on Google's repo as an initial test of "cleaning up a repo". 
Other orgs would need to consider this independently based on their own patterns. Some of the cleanup can't generalize to other orgs because of that.
> Add "Standard exec configurations" to review

- designs/2022-06-07-bazel-credential-helpers.md
- designs/2022-07-21-locating-runfiles-with-bzlmod.md
- designs/2022-08-03-platforms-on-targets.md
- designs/2022-10-17-dependency-adapter.md
- designs/2023-06-08-platform-based-flags.md
- designs/2023-06-08-standard-platform-transitions.md
In some of the proposals, the header with the metadata on the proposal does not render correctly on GitHub. Example:
```
Error in user YAML: (<unknown>): found character that cannot start any token while scanning for the next token at line 5 column 5
```
This seems to be caused by entries starting with an `@` symbol. This change fixes that.
> Fix some YAML errors in proposals

- README.md
- designs/2023-12-07-remote-local-fallback-respects-declarations.md
This is a follow up to #359 proposing to make `--remote_local_fallback` fallback to a freshly picked non-remote spawn strategy (if there are candidates left) rather than `local`.
- https://github.com/bazelbuild/bazel/issues/7202
- https://github.com/bazelbuild/bazel/issues/15519
> `--remote_local_fallback` Respects Strategy Declarations

- README.md
- designs/2023-06-04-exec-platform-scoped-spawn-strategies.md
Main changes of significance here is the renaming of 1 flag.
`--allowed_strategies_execution_platform` to specify an allowlist for an exec platform
- A _little_ less confusing to read than `--execution_platform_supported_strategies`.
- Read as "allowed strategies for execution platform".
The strictness flag `--require_platform_scoped_strategies` seems a little off but I'm unable to think up a better option at this point in time. I understand these proposals are not gospel so if I (or anyone else) comes up with better names, I'll put them forward with the implementation.
> More feedback from review of exec platform scoped spawn strategies proposal

- README.md
- designs/2024-04-26-platform-exec-settings.md
- Mark "Selectively Enabling Execution Platforms" as approved.
- Change attribute name to required_settings
- Added note about target platforms being out of scope
> Mark "Selectively Enabling Execution Platforms" as approved

- README.md
Somehow in d3a2f9a2be0149626726beee38915144d472cbf4 I managed notice the proposal was in the wrong section, and move it up into the next (still wrong) section. 🤦
> Reflect status of "exec platform scoped spawn strategies" proposal being approved in `README.md`

- README.md
I erroneously moved it to the "Dropped" section.
> Move "Extend expand_template" from Dropped to Implemented
